### ISSUE TITLE
unable to find cypress-runner container dockerfile

### ISSUE THREAD

**Issue by schose** [splunk/splunk-app-testing#17]
Hi all,

I'm testing this repo out, but failing where to get the cypress runner image which is defined here:

https://github.com/splunk/splunk-app-testing/blob/85008ebcc979df6e997637012072f707632054b7/cicd/cicd_runner.sh#L144 in $cypress_image$ . where is this defined? 

Could you provide a dockerfile or link?

Regards,

Andreas

**Comment by MichaelChristopherson** [comment]
`$cypress_image` is defined as the second argument passed to the `cicd_runner.sh`   You can see it getting called here as an example:
https://github.com/splunk/splunk-app-testing/blob/f689f2a9cbee586eefee491ffb4901bb921b74bf/.github/workflows/pipeline.yml#L67

You should see it as part of the output when the script runs here:
https://github.com/splunk/splunk-app-testing/blob/85008ebcc979df6e997637012072f707632054b7/cicd/cicd_runner.sh#L5

And see it being defined here:
https://github.com/splunk/splunk-app-testing/blob/85008ebcc979df6e997637012072f707632054b7/cicd/cicd_runner.sh#L13

**Comment by schose** [comment]
right, was working on gitlab implementation and oversee the github variable there.. makes sense, thx for clarification.
